### ISSUE TITLE
Why mobile and web endpoints

### ISSUE THREAD

**Issue by femiir** [oscarychen/django-ninja-simple-jwt#14]
nice Package you have here would be trying to use this for my jwt authentications.
i am curious to know why do you have a mobile and web endpoints… i can't really spot the difference or the use case 
do you mind explaining more

**Comment by oscarychen** [comment]
The reason I provided mobile and web endpoints have a lot to do with how and where you want to design client applications to store refresh and access tokens.

In short, token storage in web SPA has a lot of nuances for security. I find the most robust strategy is to store refresh token using a http only cookie, while access token only in memory (not persisted), and thus why I provided the web auth endpoints as such that refresh token is returned in header, and access token in response body.

On the other hand, for mobile applications, you pretty much need to have both tokens in response body.

Take a look at this answer that touches on this subject more: https://stackoverflow.com/a/54011649/10856743

**Comment by femiir** [comment]
thank you so much. makes more sense to me now.
have you considered adding this to ninja itself…??

i didn't want to use the other solutions for the obvious reasons before i saw the reddit post

**Comment by femiir** [comment]
one last one 
is there any reason why you are using a fixed algorithm i.e rsa, 
i.) any reason for not using something like Dango's SECRET_KEY and making that optional

**Comment by oscarychen** [comment]
Feel free to fork and make that a Django setting. But I think sometimes it's much easier to keep the package simple and light weight by dictating one path to take that is considered most secure.
